Toro 44208 coachtopia feedback
Tapestry-Inc/design-tokens pull request #131
Opened 2022-09-06 11:51 UTC by ejaz-tapestry

2022-09-06 20:07 UTC, p-musi approved these changes

2022-09-06 21:32 UTC, p-musi commented on src/brands/coachtopia/default/asset/logo.json
> +        "value": "logo-primary.svg"
@ejaz-tapestry, why did we create these as new logo-primary and logo-secondary instead of keeping them under the same names primary-black and primary-white?

2022-09-06 21:33 UTC, p-musi requested changes
@ejaz please review feedback

2022-09-07 12:06 UTC, ejaz-tapestry commented on src/brands/coachtopia/default/asset/logo.json
> +        "value": "logo-primary.svg"
names are changed as advised.

2022-09-20 12:19 UTC, closed without merging