Update: base color code corrected
Tapestry-Inc/design-tokens pull request #132
Opened 2022-09-06 15:22 UTC by ejaz-tapestry

2022-09-06 20:09 UTC, p-musi approved these changes

2022-09-06 21:36 UTC, p-musi commented on src/brands/stuart-weitzman/default/color/index.json
>        },
@ejaz-tapestry, instead of updating this value, can we remove "base" entirely from this file so that it doesn't override the global value?

2022-09-06 21:37 UTC, p-musi requested changes
@ejaz-tapestry please review feedback

2022-09-07 12:32 UTC, ejaz-tapestry commented on src/brands/stuart-weitzman/default/color/index.json
>        },
base color is removed

2022-09-07 13:08 UTC, p-musi approved these changes

2022-09-07 13:08 UTC, aoverstreet-tapestry approved these changes

2022-09-07 13:10 UTC, merged