Update: coachtopia brand logos added
Tapestry-Inc/design-tokens pull request #143
Opened 2022-09-20 12:16 UTC by ejaz-tapestry

2022-09-20 16:56 UTC, p-musi approved these changes

2022-09-26 19:20 UTC, p-musi requested changes
@ejaz-tapestry, please review feedback.

2022-09-29 08:58 UTC, ejaz-tapestry commented on src/brands/coachtopia/default/asset/logo.json
> -      },
@p-musi code added back

2022-09-29 14:01 UTC, p-musi approved these changes

2022-09-29 20:33 UTC, aoverstreet-tapestry commented on src/brands/coachtopia/default/effect/box-shadow.json
> +      },
@ejaz-tapestry Please remove "ltr" from this file.  
However, please update the "ltr" in global/effect/box-shadow.json with the follow:
"value": "0px -5px 10px -1px rgba(0, 0, 0, 0.05), -6px 0px 10px -5px rgba(0, 0, 0, 0.05), 6px 0px 10px -5px rgba(0, 0, 0, 0.05)"

2022-09-30 12:41 UTC, ejaz-tapestry commented on src/brands/coachtopia/default/effect/box-shadow.json
> +      },
ltr added to global setttings.

2022-09-30 15:31 UTC, p-musi approved these changes

2022-09-30 16:06 UTC, aoverstreet-tapestry approved these changes

2022-09-30 16:53 UTC, merged