Update: Toro 44561 all brand japan theme issues
Tapestry-Inc/design-tokens pull request #154
Opened 2022-09-26 13:29 UTC by ejaz-tapestry

2022-09-26 18:30 UTC, p-musi commented on src/brands/kate-spade/japan/font/face.json
> +        }
Instead of adding this as "11", we can replace "10".  We originally replaced 10 with FuturaPT-Book, but now we want to change it back.

2022-09-26 18:30 UTC, p-musi commented on src/brands/kate-spade/japan/font/family.json
> +          "value": "{font.face.11.normal.family.value}, Helvetica, Arial, Sans-serif"
Let's leave this definition to what it was, and replaced font "10" in the file above.

2022-09-26 18:54 UTC, p-musi commented on src/brands/coach/japan/utility/typography.json
> +            "value": "{size.line-height.s.value}"
According to Figma, this should be line-height-m

2022-09-26 19:01 UTC, p-musi commented on src/brands/coach/japan/asset/icon.json
> +        "link": { "value": "Link.svg" }
Can we rename this to lowercase "link.svg"?

2022-09-26 19:01 UTC, p-musi commented on src/brands/coach-outlet/japan/asset/icon.json
> +        "link": { "value": "Link.svg" }
Can we rename this to lowercase "link.svg".

2022-09-26 19:05 UTC, p-musi requested changes
@ejaz-tapestry, please review feedback.

Also, I noticed we're adding the link.svg here which was already added into Stuart Weitzman.  Really, we should move any SVG that doesn't exist in the global scope, to the global folder, and only do a brand level icon, when we want to override one from global that is already defined.

We can handle it in a separate ticket, but we should move the link.svg into global.  Probably also the loading and locate icons in SW as well.

2022-09-29 09:09 UTC, ejaz-tapestry commented on src/brands/coach/japan/utility/typography.json
> +            "value": "{size.line-height.s.value}"
line-height value changed

2022-09-29 09:09 UTC, ejaz-tapestry commented on src/brands/coach/japan/asset/icon.json
> +        "link": { "value": "Link.svg" }
case issue resolved for link icon

2022-09-29 09:09 UTC, ejaz-tapestry commented on src/brands/coach-outlet/japan/asset/icon.json
> +        "link": { "value": "Link.svg" }
case issue resolved for link icon

2022-09-29 09:30 UTC, ejaz-tapestry commented on src/brands/kate-spade/japan/font/face.json
> +        }
extra code is removed

2022-09-29 17:02 UTC, ejaz-tapestry commented on src/brands/coach-outlet/japan/asset/icon/utility/Link.svg
> +</svg>
link.svg name updated

2022-09-29 17:02 UTC, ejaz-tapestry commented on src/brands/coach/japan/asset/icon/utility/Link.svg
> +</svg>
link.svg name updated

2022-09-29 17:09 UTC, aoverstreet-tapestry approved these changes

2022-09-29 20:41 UTC, p-musi approved these changes

2022-09-29 20:42 UTC, merged