Update: Toro 50283 KS Germany theme creation
Tapestry-Inc/design-tokens pull request #168
Opened 2022-10-27 10:45 UTC by muhammad-irtiza04

2022-10-27 18:04 UTC, p-musi commented
Hi @muhammad-irtiza04,

We're not looking to copy the contents of the Japan theme over to a new German theme, we want the new German theme to be as close to the base as possible.

![Screen Shot 2022-10-27 at 1 59 10 PM](https://user-images.githubusercontent.com/97971327/198364542-b9709ed5-da13-4aa3-9bb4-0d092d55562a.png)
Please create a new folder alongside the existing "japan" folder, and name is "germany".  Each theme inherits from the default, so you only need to add the files you want to override in that theme.

Then copy the file from "src/brands/kate-spade/default/font/face.json" over to "src/brands/kate-spade/germany/font/face.json" and update the font URLs to what I posted in my comment on the ticket.

2022-10-28 10:24 UTC, muhammad-irtiza04 commented
> Hi @muhammad-irtiza04,
> 
> We're not looking to copy the contents of the Japan theme over to a new German theme, we want the new German theme to be as close to the base as possible.
> 
> ![Screen Shot 2022-10-27 at 1 59 10 PM](https://user-images.githubusercontent.com/97971327/198364542-b9709ed5-da13-4aa3-9bb4-0d092d55562a.png) Please create a new folder alongside the existing "japan" folder, and name it "germany". Each theme inherits from the default, so you only need to add the files you want to override in that theme.
> 
> Then copy the file from "src/brands/kate-spade/default/font/face.json" over to "src/brands/kate-spade/germany/font/face.json" and update the font URLs to what I posted in my comment on the ticket. No other files besides this face.json are required in the germany folder at this time.

2022-10-28 10:24 UTC, muhammad-irtiza04 commented
I have made all the changes and push the code you can review it.

2022-10-28 12:37 UTC, p-musi requested changes
Hi @muhammad-irtiza04,

This is not correct.  Please refer to my PR where I implemented the germany theme for Coach.  Only one file should be added.

https://github.com/Tapestry-Inc/design-tokens/pull/169

2022-10-28 14:07 UTC, p-musi requested changes
Hi @muhammad-irtiza04,

Looks mostly good now.  Please see review feedback comments on specific lines.  We don't want to have "(German)" appended to the font values.

2022-10-28 14:07 UTC, p-musi commented on src/brands/kate-spade/germany/font/face.json
> +            "value": "FuturaNowTextRegular(German)"
Please ensure that this is not different from the default.

2022-10-28 14:07 UTC, p-musi commented on src/brands/kate-spade/germany/font/face.json
> +            "value": ["Futura Now Text Regular (German)"]
Please ensure that this is not different from the default.

2022-10-28 14:07 UTC, p-musi commented on src/brands/kate-spade/germany/font/face.json
> +            "value": "FuturaNowHeadlineMedium(German)"
Please ensure that this is not different from the default.

2022-10-28 14:07 UTC, p-musi commented on src/brands/kate-spade/germany/font/face.json
> +            "value": ["Futura Now Headline Medium (German)"]
Please ensure that this is not different from the default.

2022-10-28 14:07 UTC, p-musi commented on src/brands/kate-spade/germany/font/face.json
> +            "value": "ITCNewBaskervilleRoman(German)"
Please ensure that this is not different from the default.

2022-10-28 14:07 UTC, p-musi commented on src/brands/kate-spade/germany/font/face.json
> +            "value": ["ITC New Baskerville Roman (German)"]
Please ensure that this is not different from the default.

2022-10-28 14:51 UTC, muhammad-irtiza04 commented on src/brands/kate-spade/germany/font/face.json
> +            "value": ["ITC New Baskerville Roman (German)"]
Resolved: Now it's according to default

2022-10-28 14:52 UTC, muhammad-irtiza04 commented on src/brands/kate-spade/germany/font/face.json
> +            "value": "FuturaNowHeadlineMedium(German)"
Resolved: Now it's according to default

2022-10-28 14:52 UTC, muhammad-irtiza04 commented on src/brands/kate-spade/germany/font/face.json
> +            "value": ["Futura Now Text Regular (German)"]
Resolved: Now it's according to default

2022-10-28 14:52 UTC, muhammad-irtiza04 commented on src/brands/kate-spade/germany/font/face.json
> +            "value": "FuturaNowTextRegular(German)"
Resolved: Now it's according to default

2022-10-28 14:54 UTC, ejaz-tapestry approved these changes

2022-10-28 18:17 UTC, p-musi approved these changes

2022-10-28 18:17 UTC, merged