Update: Toro 52784 white list dt for figma
Tapestry-Inc/design-tokens pull request #201
Opened 2022-12-20 14:05 UTC by ejaz-tapestry

Ticket: https://jira.tapestry.support/browse/TORO-52784<br>

## Changes
Trim down the new JSON to match the old JSON on Motif{}

Whitelist:

Color
Font Families
Font Sizes
Line Height

2022-12-20 16:38 UTC, aoverstreet-tapestry approved these changes

2022-12-20 18:14 UTC, aoverstreet-tapestry approved these changes

2023-01-04 19:01 UTC, p-musi requested changes
@ejaz-tapestry Can we implement the commented whitelist patterns?

CC @aoverstreet-tapestry

2023-01-13 23:51 UTC, closed without merging

2023-01-13 23:51 UTC, p-musi commented
Closing because the whitelist is being implemented in PR #216