Update: color and line-height removed
Tapestry-Inc/design-tokens pull request #210
Opened 2023-01-05 13:24 UTC by ejaz-tapestry

Ticket: https://jira.tapestry.support/browse/TORO-54724 <br>

Extra line-height and color classes are removed

2023-01-10 02:15 UTC, p-musi requested changes
Hi @ejaz-tapestry

Please review comments.

For the black/white/grey colors, I'm looking to have 6 token values for backwards compatibility.

"color-black-base"
"color-black"
"color-white-base"
"color-white"
"color-grey-base"
"color-grey"

2023-01-10 09:27 UTC, ejaz-tapestry commented on src/global/color/index.json
>          "value": "#CCCCCC"
This value is in use I got an error in the build process so I left this as it is.

2023-01-10 09:36 UTC, ejaz-tapestry commented on scripts/figma-dt/getBrandJson.js
> +                /color-carousel-indicator-bg/,
it was removed in the Black listing, SO I did not change it as it was matched and taken from the old motif File, But If you say we can add these back. and the last one is `color-carousel-indicator-bg` removed on request in this current ticket.

2023-01-12 04:28 UTC, p-musi commented on src/global/color/index.json
>          "value": "#CCCCCC"
Can we replace the use of grey.20.value with grey.base.value in the toggle.json file that uses it?  Then we can remove 20 here.

2023-01-13 23:51 UTC, closed without merging