Feature/coach outlet fonts
Tapestry-Inc/design-tokens pull request #48
Opened 2021-08-03 18:47 UTC by dmerfeld

2021-08-03 20:08 UTC, dmerfeld commented
Looks good

2021-08-03 20:09 UTC, viv-tapestry approved these changes
looks good.

2021-08-03 20:09 UTC, viv-tapestry approved these changes
looks good.

2021-08-04 03:22 UTC, ryanfitzer commented
@dmerfeld I'm on my phone, so I'm not able to check the build failure log. I expect it's due to the comment I left where you used `2` instead of a valid t-shirt size, therefore breaking the alias.

2021-08-04 12:28 UTC, dmerfeld commented
I wasn’t editing sizes, just the font names for coach outlet.

Dan Merfeld | CEO + Founder
TheoryThree Interactive llc
211 S Paterson, Suite #280
Madison, WI 53703
www.theorythree.com
c: 608-575-1066
On Aug 3, 2021, 10:23 PM -0500, Ryan Fitzer ***@***.***>, wrote:
> @dmerfeld I'm on my phone, so I'm not able to check the build failure log. I expect it's due to the comment I left where you used 2 instead of a valid t-shirt size, therefore breaking the alias.
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-08-04 16:30 UTC, ryanfitzer requested changes

2021-08-04 16:30 UTC, ryanfitzer commented on src/brands/coach-outlet/default/font/face.json
>            "woff2": {
The property name should match the font extension. Is this font `woff` or `woff2`?

2021-08-04 16:30 UTC, ryanfitzer commented on src/brands/coach-outlet/default/font/face.json
>            "woff2": {
The property name should match the font extension. Is this font `woff` or `woff2`?

2021-08-04 16:49 UTC, ryanfitzer approved these changes

2021-08-04 16:51 UTC, merged