Toro 36870 coach NA updates
Tapestry-Inc/design-tokens pull request #83
Opened 2022-07-07 15:59 UTC by ejaz-tapestry

2022-07-07 17:46 UTC, p-musi requested changes

2022-07-07 17:46 UTC, p-musi commented on src/brands/coach/default/font/face.json
> +            "value": "HelveticaLTProBold"
Can we name this "HelveticaNowVarBold" since it's not using LTPro?

2022-07-07 17:46 UTC, p-musi commented on src/brands/coach/default/font/face.json
>              "value": ["Helvetica LT Pro Bold"]
Can we also change this to "Helvetica Now Var"?

2022-07-11 09:47 UTC, ejaz-tapestry commented on src/brands/coach/default/font/face.json
> +            "value": "HelveticaLTProBold"
it was requested by Bharat to add these as bold so the font can be uniquely identified.
can be seen in this ticket in Bharat comment highlighted with red color.
https://jira.tapestry.support/browse/TORO-36870.

2022-07-11 12:36 UTC, p-musi commented on src/brands/coach/default/font/face.json
> +            "value": "HelveticaLTProBold"
We're still naming it bold, just not LTPro, since we're using the bold version of HelveticaNowVar instead of HelveticaLTPro.

2022-07-11 13:21 UTC, ejaz-tapestry commented on src/brands/coach/default/font/face.json
> +            "value": "HelveticaLTProBold"
text change done

2022-07-11 13:22 UTC, p-musi commented on src/brands/coach/default/font/face.json
> +            "value": "HelveticaNewVarBold"
Hi @ejaz-tapestry,

Small thing to change:

HelveticaNewVarBold --> HelveticaNowVarBold

2022-07-11 13:24 UTC, ejaz-tapestry commented on src/brands/coach/default/font/face.json
> +            "value": "HelveticaNewVarBold"
typo error resolved

2022-07-11 15:08 UTC, p-musi approved these changes

2022-07-11 21:42 UTC, merged