Update: Toro 35939 coach outlet na
Tapestry-Inc/design-tokens pull request #86
Opened 2022-07-12 12:50 UTC by ejaz-tapestry

2022-07-13 15:42 UTC, aoverstreet-tapestry approved these changes

2022-07-13 17:45 UTC, p-musi requested changes

2022-07-13 17:45 UTC, p-musi commented on src/brands/coach-outlet/default/font/family.json
> -          "value": "{font.face.1.condensed-bold.family.value}, Helvetica, Arial, sans-serif"
Hi @ejaz-tapestry,

As per the ticket, there will be no removal of tokens.  Can we add this back in?

2022-07-15 13:05 UTC, p-musi approved these changes

2022-07-15 13:28 UTC, merged