Update: font-face3 added back TORO-38098
Tapestry-Inc/design-tokens pull request #87
Opened 2022-07-13 15:21 UTC by ejaz-tapestry

2022-07-13 15:46 UTC, aoverstreet-tapestry approved these changes

2022-07-13 17:49 UTC, p-musi requested changes

2022-07-13 17:49 UTC, p-musi commented on src/brands/kate-spade/default/font/face.json
> +        }
We don't need to define the font more than once, we can just have the file below reference "2" when grabbing the font value.

2022-07-13 17:49 UTC, p-musi commented on src/brands/kate-spade/default/font/family.json
> +          "value": "{font.face.3.normal.family.value}, serif"
```suggestion
          "value": "{font.face.2.normal.family.value}, serif"
```
By having this reference "2", which is already defined, we don't need to define a "3" in the first file.

2022-07-13 17:49 UTC, p-musi commented on src/brands/kate-spade/default/font/family.json
> +          "value": "{font.face.3.light.family.value}, serif"
```suggestion
          "value": "{font.face.2.normal.family.value}, serif"
```
By having this reference "2", which is already defined, we don't need to define a "3" in the first file.

2022-07-15 10:55 UTC, ejaz-tapestry commented on src/brands/kate-spade/default/font/family.json
> +          "value": "{font.face.3.light.family.value}, serif"
changes done

2022-07-15 10:55 UTC, ejaz-tapestry commented on src/brands/kate-spade/default/font/face.json
> +        }
extra code removed

2022-07-15 10:56 UTC, ejaz-tapestry commented on src/brands/kate-spade/default/font/family.json
> +          "value": "{font.face.3.normal.family.value}, serif"
changes done

2022-07-15 13:15 UTC, p-musi approved these changes

2022-07-15 14:00 UTC, merged